# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- task: TfxInstaller@3
  inputs:
    version: 'v0.11.x'

- task: QueryAzureDevOpsExtensionVersion@3
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'Marketplace'
    publisherId: 'NevinCansel'
    extensionId: 'mirror-repos'
    versionAction: 'Patch'

- task: PackageAzureDevOpsExtension@3
  inputs:
    rootFolder: 
    updateTasksVersion: false
    extensionVisibility: 'public'
    extensionPricing: 'free'


- task: PublishAzureDevOpsExtension@3
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'Marketplace'
    fileType: 'vsix'
    vsixFile: '*.vsix'
    publisherId: 'NevinCansel'
    extensionId: 'mirror-repos'
    extensionName: 'Mirror Repositories'
    updateTasksVersion: false
    extensionVisibility: 'public'
    extensionPricing: 'free'